version: '3.8'
services:
  ecommerce:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/ecommerce
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_PASSWORD=eshop123
      - SPRING_DATASOURCE_USERNAME=alina
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlserver/ecommerce
    volumes:
      - ./:/ecommerce-app
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=eshop123
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=alina
      - MYSQL_PASSWORD=eshop123
      - MYSQL_DATABASE=ecommerce
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config: