# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Checkout
      uses: actions/checkout@v4
      if: github.ref == 'refs/heads/main'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      if: github.ref == 'refs/heads/main'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      if: github.ref == 'refs/heads/main'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      if: github.ref == 'refs/heads/main'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      if: github.ref == 'refs/heads/main'
      with:
        context: .
        push: true
        tags: aalina/ecommerce:latest
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
          service: 'ecommerce-cloud-run'
          image: 'aalina/ecommerce:latest'
      if: github.ref == 'refs/heads/main'